services:
  backend:
    image: nodejs-backend
    container_name: library-management-system-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    volumes:
      - ./src:/app/src

  postgres-db:
    image: postgres:15
    container_name: library-management-system-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
