services:
  backend:
    image: nodejs-backend
    container_name: library-management-system-backend
    build: .
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  postgres-db:
    image: postgres:15
    container_name: library-management-system-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
